### ISSUE TITLE
Throws key null error when class is ordered in certain way

### ISSUE THREAD

**Issue by unional** [aurelia/dependency-injection#144]
**I'm submitting a bug report**

* **Library Version:**
1.3.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x|Windows [8|8.1]

* **Node Version:**
7.3.0, 7.5.0

* **NPM Version:**
4.0.5

* **Language:**
TypeScript 2.2.1

**Current behavior:**
The following code throws error:

```ts
import test from 'ava'
import { Container, singleton } from 'aurelia-dependency-injection'

@singleton()
class Depender {
  constructor(private dep: Dependent) { }
  get() {
    return this.dep.foo
  }
}

class Dependent {
  foo = 'foo'
}

test('first test', t => {
  const container = new Container()

  const actual = container.get(Depender)

  t.is(actual.get(), 'foo')
})
```

The error is:
```sh
Error: Error invoking Depender. Check the inner error for details.
  ------------------------------------------------
  Inner Error:
  Message: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?
  Inner Error Stack:
  Error: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?
      at validateKey (/Users/hwong/github/unional/some-issues/node_modules/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js:396:11)
      at Container.get (/Users/hwong/github/unional/some-issues/node_modules/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js:593:5)
      at Object.invoke (/Users/hwong/github/unional/some-issues/node_modules/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js:445:31)
      at InvocationHandler.invoke (/Users/hwong/github/unional/some-issues/node_modules/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js:416:16
6)
...
```

If the `Dependent` class is defined before `Depender` class, the code will pass.

i.e. this passes:

```ts
import test from 'ava'

import { Container, singleton } from 'aurelia-dependency-injection'

class Dependent {
  foo = 'foo'
}

@singleton()
class Depender {
  constructor(private dep: Dependent) { }
  get() {
    return this.dep.foo
  }
}

test('first test', t => {
  const container = new Container()

  const actual = container.get(Depender)

  t.is(actual.get(), 'foo')
})
```

Here is the repro: https://github.com/unional/issues/tree/aurelia-di-order-issue

```sh
git clone https://github.com/unional/issues.git
cd issues
git checkout aurelia-di-order-issue
npm install
npm test
```

**Comment by EisenbergEffect** [comment]
The problem here is that classes don't work like vars. Vars are hoisted to the top of the function. Classes are never hoisted. So, it's literally not defined. Nothing to do with Aurelia.

**Comment by unional** [comment]
> The problem here is that classes don't work like vars. Vars are hoisted to the top of the function. Classes are never hoisted.

I think that has nothing to do with this issue.

When `container.get(Depender)` is called, both `Depender` and `Dependent` are already defined.

**Comment by unional** [comment]
Meaning, this can be avoided if `@singleton` delay capture of the constructor parameter types.

**Comment by EisenbergEffect** [comment]
`@singleton` doesn't capture anything. You are referring to work that the TS compiler is doing. It is the thing that is encoding the type data.

**Comment by unional** [comment]
Yes, you are correct.

Updating the test code:

```ts
import test from 'ava'

import { Container, autoinject } from 'aurelia-dependency-injection'


@autoinject()
class Depender {
  constructor(private dep: Dependent) {
    console.log(dep)
  }
  get() {
    return this.dep.foo
  }
}
class Dependent {
  foo = 'foo'
}

test('first test', t => {
  const container = new Container()
  const actual = container.get(Depender)

  t.is(actual.get(), 'foo')
})
```

Transpile to:
```js
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
Object.defineProperty(exports, "__esModule", { value: true });
var ava_1 = require("ava");
var aurelia_dependency_injection_1 = require("aurelia-dependency-injection");
var Depender = (function () {
    function Depender(dep) {
        this.dep = dep;
        console.log(dep);
    }
    Depender.prototype.get = function () {
        return this.dep.foo;
    };
    return Depender;
}());
Depender = __decorate([
    aurelia_dependency_injection_1.autoinject(),
    __metadata("design:paramtypes", [Dependent])
], Depender);
var Dependent = (function () {
    function Dependent() {
        this.foo = 'foo';
    }
    return Dependent;
}());
ava_1.default('first test', function (t) {
    var container = new aurelia_dependency_injection_1.Container();
    var actual = container.get(Depender);
    t.is(actual.get(), 'foo');
});
```

The `Dependent` class is transpiled to `var` so it is hoisted.
So I don't see why it doesn't work.

**Comment by unional** [comment]
I look more into the transpiled code and it seems like a bug in NodeJS?

```js
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
Object.defineProperty(exports, "__esModule", { value: true });
var ava_1 = require("ava");
var aurelia_dependency_injection_1 = require("aurelia-dependency-injection");
var Depender = (function () {
    function Depender(dep) {
        this.dep = dep;
    }
    Depender.prototype.get = function () {
        return this.dep.foo;
    };
    return Depender;
}());
Depender = __decorate([
    aurelia_dependency_injection_1.autoinject(),
    __metadata("design:paramtypes", (function() { console.log('dummy', dummy, Dependent); return [Dependent]; }()))
], Depender);
var Dependent = (function () {
    function Dependent() {
        this.foo = 'foo';
    }
    return Dependent;
}());
var dummy = 1;
ava_1.default('first test', function (t) {
    var container = new aurelia_dependency_injection_1.Container();
    var actual = container.get(Depender);
    t.is(actual.get(), 'foo');
});
//# sourceMappingURL=index.spec.js.map
```
prints out `dummy undefined undefined`.

Top level `var` is not hoisted ???

**Comment by unional** [comment]
Got it. Nevermind. Hoisting 101. The variable is hoisted but not the initialization.

**Comment by unional** [comment]
> Meaning, this can be avoided if @singleton delay capture of the constructor parameter types.

For reference, `@autoinject()` is transpiled to:

```ts
Depender = __decorate([
    aurelia_dependency_injection_1.autoinject(),
    __metadata("design:paramtypes", [Dependent])
], Depender);
var Dependent = ...
```
So the `Dependent` is captured (by TS, not by the decorator) before initialization.
