### ISSUE TITLE
Uncaught Error: key cannot be null or undefined.

### ISSUE THREAD

**Issue by kplatter** [aurelia/dependency-injection#36]
If I mistakenly import a object from a location where it does not exist like

```import {EventAggregator} from 'aurelia-framework';``` 

system.js imports EventAggregator as undefined, then when I inject the EventAggregator into my element it gives the error below

```
Uncaught Error: key cannot be null or undefined.
    at Container.get [as superGet] (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.8.1/container.js:122:19)
    at Container.eval (eval at evaluate (unknown source), <anonymous>:1:6)
    at Object.InjectedScript._evaluateOn (<anonymous>:895:55)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluateOnCallFrame (<anonymous>:954:21)
    at Container.elementContainerGet [as get] (http://localhost:9000/jspm_packages/github/aurelia/templating@0.12.1/view-factory.js:43:16)
    at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.8.1/container.js:200:30)
    at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.8.1/container.js:79:48)
    at Container.get [as superGet] (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.8.1/container.js:136:28)
    at Container.elementContainerGet [as get] (http://localhost:9000/jspm_packages/github/aurelia/templating@0.12.1/view-factory.js:43:17)
```

According to @PWKad "I believe there is an open issue for that but if I remember correctly the problem is that it is trying to find a container by key but the key passed in was null. You could open an issue on DI to remember for later to improve that error message."

If possible please improve error message.

**Comment by EisenbergEffect** [comment]
What would you prefer? It could say "key cannot be null or undefined. Did you correctly import the symbol?" Other than that, I'm not sure what else we can do. From the DI's perspective, it was passed undefined.

**Comment by PWKad** [comment]
I think this is related to #24

**Comment by EisenbergEffect** [comment]
Unfortunately, there's no way to include the "name" because from DI's perspective, it just gets "undefined".

**Comment by PWKad** [comment]
I think the recommendation was to add something like `key cannot be null or undefined. (Are you trying to inject something that doesn't exist with DI?)` to point someone in the right direction, like you mentioned.  If that sounds good I can submit a PR.

**Comment by EisenbergEffect** [comment]
Yep, sounds good. Submit the PR and we'll get it in for the upcoming release.
